package com.hzlwyykj.model;

public class WorkConditionVo extends BaseVo {
	 private String workorderid;

	    /**
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column t_workorder.customerid
	     *
	     * 
	     */
	    private Integer customerid;

	    /**
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column t_workorder.customername
	     *
	     * 
	     */
	    private String customername;

	    /**
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column t_workorder.centificatenumber
	     *
	     */
	    private String centificatenumber;

	    /**
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column t_workorder.aging
	     *
	     * 
	     */
	    private Integer aging;

	    /**
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column t_workorder.problemtype
	     *
	     * 
	     */
	    private Integer problemtype;

	    /**
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column t_workorder.handlegroup
	     *
	     * 
	     */
	    private Integer handlegroup;

	    /**
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column t_workorder.handleperson
	     *
	     * 
	     */
	    private Integer handleperson;

	    /**
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column t_workorder.urgencylevel
	     *
	     * 
	     */
	    private Integer urgencylevel;

	    /**
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column t_workorder.status
	     *
	     * 
	     */
	    private Integer status;

		public String getWorkorderid() {
			return workorderid;
		}

		public void setWorkorderid(String workorderid) {
			this.workorderid = workorderid;
		}

		public Integer getCustomerid() {
			return customerid;
		}

		public void setCustomerid(Integer customerid) {
			this.customerid = customerid;
		}

		public String getCustomername() {
			return customername;
		}

		public void setCustomername(String customername) {
			this.customername = customername;
		}

		public String getCentificatenumber() {
			return centificatenumber;
		}

		public void setCentificatenumber(String centificatenumber) {
			this.centificatenumber = centificatenumber;
		}

		public Integer getAging() {
			return aging;
		}

		public void setAging(Integer aging) {
			this.aging = aging;
		}

		public Integer getProblemtype() {
			return problemtype;
		}

		public void setProblemtype(Integer problemtype) {
			this.problemtype = problemtype;
		}

		public Integer getHandlegroup() {
			return handlegroup;
		}

		public void setHandlegroup(Integer handlegroup) {
			this.handlegroup = handlegroup;
		}

		public Integer getHandleperson() {
			return handleperson;
		}

		public void setHandleperson(Integer handleperson) {
			this.handleperson = handleperson;
		}

		public Integer getUrgencylevel() {
			return urgencylevel;
		}

		public void setUrgencylevel(Integer urgencylevel) {
			this.urgencylevel = urgencylevel;
		}

		public Integer getStatus() {
			return status;
		}

		public void setStatus(Integer status) {
			this.status = status;
		}
	    
	    
}
